# Generated by Django 3.0.6 on 2020-06-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='repositories', to='github.Tag', verbose_name='tag'),
        ),
    ]
